server:
  port: 8089

spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2
  datasource:
    # url: jdbc:h2:mem:~/portfoliodb;DB_CLOSE_DELAY=-1
    url: jdbc:h2:file:~/portfoliodb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
